name: "setup_cache"
description: "sets up the shared cache"
inputs:
  compiler:
    required: true
    type: string
  build_type:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Cache CMake dependency source code
      uses: actions/cache@v4
      env:
        cache-name: cache-cmake-dependency-sources
      with:
        path: ${{github.workspace}}/build/_deps/*-src
        key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**') }}
        restore-keys: |
          ${{ env.cache-name }}
    - name: Cache CMake dependency build objects
      uses: actions/cache@v4
      env:
        cache-name: cache-cmake-dependency-builds
      with:
        path: |
           ${{github.workspace}}/build/_deps/*-build
           ${{github.workspace}}/build/_deps/*-subbuild
        key: ${{ env.cache-name }}-${{ inputs.compiler }}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.ccache
        key: ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}
