name: setup_cache
description: "sets up the shared cache"
inputs:
  compiler:
    required: true
    type: string
  build_type:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Cache CMake dependency source code
      uses: actions/cache@v4.2.2
      with:
        path: '~/.cache/CPM'
        key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-cpm-

    - name: Cache ccache
      uses: actions/cache@v4.2.2
      with:
        path: ${{ env.CCACHE_CONFIGPATH }}
        key: ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}
