name: Setup Cache
description: "sets up the shared cache"
inputs:
  preset:
    required: true
    description: CMake preset

runs:
  using: "composite"
  steps:
    - name: Set cache environment variables
      shell: bash
      run: |
        echo "CPM_SOURCE_CACHE=${{ github.workspace }}/.cache/CPM" >> $GITHUB_ENV
        echo "CCACHE_DIR=${{ github.workspace }}/.cache/ccache" >> $GITHUB_ENV

    - name: Cache CMake dependency source code
      uses: actions/cache@v4.3.0
      with:
        path: ${{ github.workspace }}/.cache/CPM
        key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-cpm-

    - name: Cache ccache
      uses: actions/cache@v4.3.0
      with:
        path: ${{ github.workspace }}/.cache/ccache
        key: ${{ runner.os }}-${{ inputs.preset }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.preset }}
