name: Setup Build Environment
description: Install dependencies for building Adaptive SPH

inputs:
  preset:
    description: CMake preset
    required: true

runs:
  using: composite
  steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xorg-dev \
          libwayland-dev \
          wayland-protocols \
          libxkbcommon-dev \
          libegl1-mesa-dev \
          libgles2-mesa-dev \
          libc++-20-dev \
          libc++abi-20-dev

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@033219e2d69dd4d3e873e217eb385fdd4b4438f4
      with:
        version: 1.4.328.1
        cache: true

    - name: Install CUDA Toolkit (Windows)
      if: runner.os == 'Windows'
      uses: Jimver/cuda-toolkit@v0.2.24
      with:
        method: network
        sub-packages: '["nvcc", "cudart", "thrust"]'
        log-file-suffix: '${{github.job}}-${{ inputs.preset }}.txt'

    - name: Install CUDA Toolkit (Linux)
      if: runner.os == 'Linux'
      uses: Jimver/cuda-toolkit@v0.2.28
      with:
        method: network
        sub-packages: '["nvcc", "cudart", "thrust"]'
        log-file-suffix: '${{github.job}}-${{ inputs.preset }}.txt'
