name: Formatting Check
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  clang-format-check:
    name: clang-format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run clang-format check
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: '20'
  cmake-format-check:
    name: cmake-format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run cmake-format check
        uses: puneetmatharu/cmake-format-lint-action@v1.0.6
        with:
          args: --check -c .cmake-format.yaml
